"""empty message

Revision ID: 080f55432d0d
Revises: 7fd3a65efcb4
Create Date: 2023-09-14 14:19:11.812862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080f55432d0d'
down_revision = '7fd3a65efcb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('group', sa.VARCHAR(length=10), nullable=False),
    sa.Column('action', sa.VARCHAR(length=10), nullable=False),
    sa.Column('time', sa.VARCHAR(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'name', 'group', 'action', 'time', name='unique_event')
    )
    # ### end Alembic commands ###
